name: Publish

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore "./BatchMuxed_Sub"
    - name: Build
      shell: bash
      run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="BatchMuxed_Sub-$tag-win-x64"
          # Build everything
          dotnet publish ./BatchMuxed_Sub -r win-x64 -p:PublishSingleFile=true --self-contained false -c Release -o "$release_name"
          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
          # Delete output directory
          rm -r "$release_name"
          
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "BatchMuxed_Sub*"
