- name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v1.8.1
  on: [push]
  steps:
- uses: actions/checkout@v2
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '6.0.x'
    include-prerelease: true
- run: dotnet build BatchMuxer_Sub
